/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        accent: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        navy: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        }
      },
      animation: {
        'fade-in': 'fadeIn 0.8s ease-in-out',
        'fade-in-up': 'fadeInUp 1s ease-out',
        'fade-in-delayed': 'fadeIn 1s ease-in-out 0.5s both',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.6s ease-out',
        'slide-in-left-bounce': 'slideInLeftBounce 1s ease-out',
        'slide-in-right-bounce': 'slideInRightBounce 1s ease-out',
        'slide-down-bounce': 'slideDownBounce 1s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out infinite 2s',
        'float-gentle': 'floatGentle 4s ease-in-out infinite',
        'float-gentle-delayed': 'floatGentle 4s ease-in-out infinite 1s',
        'float-gentle-delayed-2': 'floatGentle 4s ease-in-out infinite 2s',
        'float-sparkle': 'floatSparkle 3s ease-in-out infinite',
        'float-sparkle-delayed': 'floatSparkle 3s ease-in-out infinite 1s',
        'float-sparkle-delayed-2': 'floatSparkle 3s ease-in-out infinite 2s',
        'float-sparkle-delayed-3': 'floatSparkle 3s ease-in-out infinite 1.5s',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'pulse-very-slow': 'pulse 4s ease-in-out infinite',
        'pulse-gentle': 'pulseGentle 2s ease-in-out infinite',
        'dashboard-float': 'dashboardFloat 8s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'glow-pulse-red': 'glowPulseRed 2s ease-in-out infinite',
        'glow-pulse-green': 'glowPulseGreen 2s ease-in-out infinite',
        'glow-button': 'glowButton 3s ease-in-out infinite',
        'text-glow': 'textGlow 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s ease-in-out infinite',
        'sparkle-rotate': 'sparkleRotate 3s ease-in-out infinite',
        'sparkle-rotate-delayed': 'sparkleRotate 3s ease-in-out infinite 1s',
        'sparkle-container': 'sparkleContainer 4s ease-in-out infinite',
        'gradient-shift': 'gradientShift 8s ease-in-out infinite',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'rotate-slow': 'rotateSlow 20s linear infinite',
        'draw-circle': 'drawCircle 2s ease-out',
        'draw-circle-delayed': 'drawCircle 2s ease-out 0.5s',
        'draw-circle-delayed-2': 'drawCircle 2s ease-out 1s',
        'bar-grow': 'barGrow 1s ease-out',
        // Ripple effect animations
        'ripple-subtle-1': 'rippleSubtle 4s ease-out infinite',
        'ripple-subtle-2': 'rippleSubtle 5s ease-out infinite 1s',
        'ripple-subtle-3': 'rippleSubtle 6s ease-out infinite 2s',
        'ripple-blue-1': 'rippleBlue 3s ease-out infinite',
        'ripple-cyan-1': 'rippleCyan 3.5s ease-out infinite 0.5s',
        'ripple-purple-1': 'ripplePurple 4s ease-out infinite 1s',
        'ripple-blue-2': 'rippleBlue 5s ease-out infinite 1.5s',
        'ripple-cyan-2': 'rippleCyan 4.5s ease-out infinite 2s',
        'ripple-card-1': 'rippleCard 3s ease-out infinite',
        'ripple-card-2': 'rippleCard 3.5s ease-out infinite 0.8s',
        'ripple-card-3': 'rippleCard 4s ease-out infinite 1.2s',
        'ripple-dynamic-1': 'rippleDynamic 2s ease-out infinite',
        'ripple-dynamic-2': 'rippleDynamic 2.5s ease-out infinite 0.3s',
        'ripple-dynamic-3': 'rippleDynamic 3s ease-out infinite 0.6s',
        'ripple-dynamic-4': 'rippleDynamic 2.2s ease-out infinite 0.9s',
        'ripple-dynamic-5': 'rippleDynamic 2.8s ease-out infinite 1.2s',
        'ripple-dynamic-6': 'rippleDynamic 2.4s ease-out infinite 1.5s',
        'ripple-dynamic-7': 'rippleDynamic 3.2s ease-out infinite 1.8s',
        'ripple-dynamic-8': 'rippleDynamic 2.6s ease-out infinite 2.1s',
        'ripple-report-1': 'rippleReport 4s ease-out infinite',
        'ripple-report-2': 'rippleReport 4.5s ease-out infinite 1s',
        'ripple-report-3': 'rippleReport 5s ease-out infinite 2s',
        'ripple-document-1': 'rippleDocument 3s ease-out infinite',
        'ripple-document-2': 'rippleDocument 3.5s ease-out infinite 0.7s',
        'ripple-communication-1': 'rippleCommunication 2.8s ease-out infinite',
        'ripple-communication-2': 'rippleCommunication 3.2s ease-out infinite 0.9s',
        'ripple-chart-1': 'rippleChart 3.5s ease-out infinite',
        'ripple-chart-2': 'rippleChart 3s ease-out infinite 0.8s',
        'ripple-forecast-1': 'rippleForecast 3.8s ease-out infinite',
        'ripple-forecast-2': 'rippleForecast 4.2s ease-out infinite 0.6s',
        'ripple-forecast-3': 'rippleForecast 4.6s ease-out infinite 1.2s',
        'ripple-forecast-4': 'rippleForecast 5s ease-out infinite 1.8s',
        'ripple-prediction-1': 'ripplePrediction 2.5s ease-out infinite',
        'ripple-prediction-2': 'ripplePrediction 3s ease-out infinite 0.7s',
        'ripple-invoice-1': 'rippleInvoice 3.2s ease-out infinite',
        'ripple-invoice-2': 'rippleInvoice 2.8s ease-out infinite 0.9s',
        'ripple-cash-1': 'rippleCash 3s ease-out infinite',
        'ripple-alert-1': 'rippleAlert 2.5s ease-out infinite',
        'ripple-consolidation-1': 'rippleConsolidation 4s ease-out infinite',
        'ripple-consolidation-2': 'rippleConsolidation 4.5s ease-out infinite 0.8s',
        'ripple-consolidation-3': 'rippleConsolidation 5s ease-out infinite 1.6s',
        'ripple-consolidation-4': 'rippleConsolidation 5.5s ease-out infinite 2.4s',
        'ripple-network-1': 'rippleNetwork 3s ease-out infinite',
        'ripple-network-2': 'rippleNetwork 3.5s ease-out infinite 0.6s',
        'ripple-network-3': 'rippleNetwork 4s ease-out infinite 1.2s',
        'ripple-integration-1': 'rippleIntegration 3.2s ease-out infinite',
        'ripple-integration-2': 'rippleIntegration 3.8s ease-out infinite 0.7s',
        'ripple-integration-3': 'rippleIntegration 4.2s ease-out infinite 1.4s',
        'ripple-summary-1': 'rippleSummary 4s ease-out infinite',
        'ripple-summary-2': 'rippleSummary 3.5s ease-out infinite 0.8s',
        'ripple-summary-3': 'rippleSummary 4.5s ease-out infinite 1.6s',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeftBounce: {
          '0%': { opacity: '0', transform: 'translateX(-100px) scale(0.8)' },
          '60%': { opacity: '0.8', transform: 'translateX(10px) scale(1.05)' },
          '100%': { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        slideInRightBounce: {
          '0%': { opacity: '0', transform: 'translateX(100px) scale(0.8)' },
          '60%': { opacity: '0.8', transform: 'translateX(-10px) scale(1.05)' },
          '100%': { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        slideDownBounce: {
          '0%': { opacity: '0', transform: 'translateY(-100px) scale(0.8)' },
          '60%': { opacity: '0.8', transform: 'translateY(10px) scale(1.05)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(1deg)' },
        },
        floatGentle: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        floatSparkle: {
          '0%, 100%': { transform: 'translateY(0px) scale(1)' },
          '50%': { transform: 'translateY(-15px) scale(1.2)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(59, 130, 246, 0.6)' },
        },
        pulseGentle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        glowPulse: {
          '0%, 100%': { textShadow: '0 0 10px rgba(255, 255, 255, 0.5)' },
          '50%': { textShadow: '0 0 20px rgba(255, 255, 255, 0.8), 0 0 30px rgba(59, 130, 246, 0.5)' },
        },
        glowPulseRed: {
          '0%, 100%': { textShadow: '0 0 10px rgba(248, 113, 113, 0.5)' },
          '50%': { textShadow: '0 0 20px rgba(248, 113, 113, 0.8)' },
        },
        glowPulseGreen: {
          '0%, 100%': { textShadow: '0 0 10px rgba(34, 197, 94, 0.5)' },
          '50%': { textShadow: '0 0 20px rgba(34, 197, 94, 0.8)' },
        },
        glowButton: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(34, 211, 238, 0.4)' },
          '50%': { boxShadow: '0 0 40px rgba(34, 211, 238, 0.7), 0 0 60px rgba(59, 130, 246, 0.3)' },
        },
        textGlow: {
          '0%, 100%': { textShadow: '0 0 10px rgba(255, 255, 255, 0.3)' },
          '50%': { textShadow: '0 0 20px rgba(255, 255, 255, 0.6), 0 0 30px rgba(34, 211, 238, 0.4)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        sparkleRotate: {
          '0%, 100%': { transform: 'rotate(0deg) scale(1)' },
          '25%': { transform: 'rotate(90deg) scale(1.2)' },
          '50%': { transform: 'rotate(180deg) scale(1)' },
          '75%': { transform: 'rotate(270deg) scale(1.2)' },
        },
        sparkleContainer: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        rotateSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        drawCircle: {
          '0%': { strokeDasharray: '0, 100' },
          '100%': { strokeDasharray: '60, 100' },
        },
        barGrow: {
          '0%': { transform: 'scaleY(0)' },
          '100%': { transform: 'scaleY(1)' },
        },
        dashboardFloat: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) rotate(0deg)' },
          '25%': { transform: 'translateY(-15px) translateX(10px) rotate(1deg)' },
          '50%': { transform: 'translateY(-10px) translateX(-5px) rotate(-0.5deg)' },
          '75%': { transform: 'translateY(-20px) translateX(15px) rotate(0.5deg)' },
        },
        // Ripple effect keyframes
        rippleSubtle: {
          '0%': { transform: 'scale(0)', opacity: '0.8' },
          '50%': { opacity: '0.4' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rippleBlue: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '50%': { opacity: '0.3' },
          '100%': { transform: 'scale(3)', opacity: '0' },
        },
        rippleCyan: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '50%': { opacity: '0.25' },
          '100%': { transform: 'scale(3.5)', opacity: '0' },
        },
        ripplePurple: {
          '0%': { transform: 'scale(0)', opacity: '0.4' },
          '50%': { opacity: '0.2' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rippleCard: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '50%': { opacity: '0.3' },
          '100%': { transform: 'scale(8)', opacity: '0' },
        },
        rippleDynamic: {
          '0%': { transform: 'scale(0)', opacity: '0.8' },
          '50%': { opacity: '0.4' },
          '100%': { transform: 'scale(6)', opacity: '0' },
        },
        rippleReport: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '50%': { opacity: '0.25' },
          '100%': { transform: 'scale(5)', opacity: '0' },
        },
        rippleDocument: {
          '0%': { transform: 'scale(0)', opacity: '0.7' },
          '50%': { opacity: '0.35' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rippleCommunication: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '50%': { opacity: '0.3' },
          '100%': { transform: 'scale(5)', opacity: '0' },
        },
        rippleChart: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '50%': { opacity: '0.25' },
          '100%': { transform: 'scale(6)', opacity: '0' },
        },
        rippleForecast: {
          '0%': { transform: 'scale(0)', opacity: '0.4' },
          '50%': { opacity: '0.2' },
          '100%': { transform: 'scale(4.5)', opacity: '0' },
        },
        ripplePrediction: {
          '0%': { transform: 'scale(0)', opacity: '0.8' },
          '50%': { opacity: '0.4' },
          '100%': { transform: 'scale(3)', opacity: '0' },
        },
        rippleInvoice: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '50%': { opacity: '0.3' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rippleCash: {
          '0%': { transform: 'scale(0)', opacity: '0.7' },
          '50%': { opacity: '0.35' },
          '100%': { transform: 'scale(3.5)', opacity: '0' },
        },
        rippleAlert: {
          '0%': { transform: 'scale(0)', opacity: '0.8' },
          '50%': { opacity: '0.4' },
          '100%': { transform: 'scale(3)', opacity: '0' },
        },
        rippleConsolidation: {
          '0%': { transform: 'scale(0)', opacity: '0.3' },
          '50%': { opacity: '0.15' },
          '100%': { transform: 'scale(5)', opacity: '0' },
        },
        rippleNetwork: {
          '0%': { transform: 'scale(0)', opacity: '0.6' },
          '50%': { opacity: '0.3' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        rippleIntegration: {
          '0%': { transform: 'scale(0)', opacity: '0.5' },
          '50%': { opacity: '0.25' },
          '100%': { transform: 'scale(4.5)', opacity: '0' },
        },
        rippleSummary: {
          '0%': { transform: 'scale(0)', opacity: '0.4' },
          '50%': { opacity: '0.2' },
          '100%': { transform: 'scale(6)', opacity: '0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      screens: {
        'xs': '475px',
      },
    },
  },
  plugins: [],
};